title: My Git Learning Journey
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ixtzib.github.io/prueba3

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
search.tokenizer_separator: /[\s/]+/

# Display the relative url in search results
# Supports true (default) or false
search.rel_url: false

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

  # Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts:
  warning:
    title: Warning
    color: red

  highlight:
    title: Highlight
    color: yellow
  
  note:
    title: Note
    color: purple

  important:
    title: Important
    color: blue

  new:
    title: New
    color: green
